#!/bin/bash

echo "🔧 Postgres.app Permission Fix Guide"
echo "======================================"
echo ""
echo "The error you're experiencing is due to macOS security restrictions."
echo "Here are the steps to fix it:"
echo ""
echo "📋 Method 1: Grant Permission Through System Preferences"
echo "1. Open System Preferences/Settings"
echo "2. Go to Security & Privacy (or Privacy & Security on newer macOS)"
echo "3. Click on the 'Privacy' tab"
echo "4. Select 'Full Disk Access' from the left panel"
echo "5. Click the lock icon and enter your password"
echo "6. Click the '+' button and add Postgres.app"
echo "7. Restart Postgres.app"
echo ""
echo "📋 Method 2: Terminal Permission Grant"
echo "1. In Terminal, run: sudo spctl --master-disable"
echo "2. Open Postgres.app"
echo "3. Try connecting again"
echo "4. Re-enable security: sudo spctl --master-enable"
echo ""
echo "📋 Method 3: Open Helper Application Directly"
echo "1. Open Finder and go to Applications"
echo "2. Right-click Postgres.app → Show Package Contents"
echo "3. Navigate to Contents/Versions/[version]/bin/"
echo "4. Double-click 'postgres' and click 'Open' when prompted"
echo "5. This grants permission to the helper app"
echo ""
echo "📋 Method 4: Use Alternative PostgreSQL Installation"
echo "If Postgres.app continues to have issues, consider:"
echo "brew install postgresql"
echo "brew services start postgresql"
echo ""
echo "🔄 After fixing permissions, run:"
echo "node scripts/create-admin-user-robust.js"
